# Generated by Django 3.1 on 2022-01-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20220101_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='talk',
            field=models.CharField(max_length=140),
        ),
    ]
